# Generated by Django 4.1.7 on 2023-03-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_movie_rating_delete_film_delete_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="movie_id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="rating",
            name="user_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
