# Generated by Django 4.1.7 on 2023-03-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_movie_movie_id_alter_rating_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.FloatField(),
        ),
    ]
