# Generated by Django 4.1.7 on 2023-03-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_rating_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="movie_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
